// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngkmduwclohevayysnok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5na21kdXdjbG9oZXZheXlzbm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjgyODMsImV4cCI6MjA2MTAwNDI4M30.maonKhV0wZwNKULz76ZOFqeeXDxMT7M9GUt0AA48ybA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);